// Generate src/schema.ts from the Classic Chess OpenAPI contract with
// openapi-typescript. Run `npm ci --prefix codegen` once, then
// `node codegen/generate.mjs` to write or `--check` to verify.
//
// The generator has its own lock because openapi-typescript drives the
// TypeScript compiler API (`ts.factory`), which TypeScript 7's native package
// no longer ships. codegen/ pins TypeScript 6, the newest line with that API,
// and overrides openapi-typescript's `^5.x` peer range to accept it; the SDK
// itself still builds with TypeScript 7.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const packageRoot = new URL('..', import.meta.url);
// A standalone export carries the contract; the monorepo serves it from the site.
const specCandidates = [
  new URL('contracts/openapi.yaml', packageRoot),
  new URL('../../core/templates/core/pages/openapi.yaml', packageRoot),
];
const spec = specCandidates.find(candidate => existsSync(candidate));
if (!spec) {
  throw new Error('OpenAPI contract not found in contracts/ or the website templates.');
}
const target = new URL('src/schema.ts', packageRoot);
const header = '// Generated by codegen/generate.mjs (openapi-typescript) from OpenAPI. Do not edit.\n';

const ast = await openapiTS(pathToFileURL(fileURLToPath(spec)), {
  // One exported alias per component schema, named exactly as in the contract.
  rootTypes: true,
  rootTypesNoSchemaPrefix: true,
});
const output = header + astToString(ast);

if (process.argv.includes('--check')) {
  const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
  if (current !== output) {
    process.stderr.write('SDK types differ from OpenAPI; run `node codegen/generate.mjs`.\n');
    process.exit(1);
  }
} else {
  writeFileSync(target, output);
}
