"""Generate the SDK response types from the repository's OpenAPI contract."""
import argparse
import json
from pathlib import Path

import yaml

PACKAGE = Path(__file__).resolve().parents[1]
SPEC = PACKAGE / 'contracts/openapi.yaml'
if not SPEC.is_file():
    SPEC = PACKAGE.parents[1] / 'core/templates/core/pages/openapi.yaml'


def ts_type(schema):
    if '$ref' in schema:
        return schema['$ref'].rsplit('/', 1)[1]
    if 'const' in schema:
        return json.dumps(schema['const'])
    if 'enum' in schema:
        return ' | '.join(json.dumps(value) for value in schema['enum'])
    for key, separator in (('allOf', ' & '), ('anyOf', ' | '), ('oneOf', ' | ')):
        if key in schema:
            return separator.join(f'({ts_type(item)})' for item in schema[key])
    kind = schema.get('type')
    if isinstance(kind, list):
        return ' | '.join(ts_type({**schema, 'type': member}) for member in kind)
    if kind == 'array':
        return f'Array<{ts_type(schema.get("items", {}))}>'
    if kind == 'object':
        properties = schema.get('properties', {})
        required = schema.get('required', [])
        members = [
            f'{json.dumps(name)}{"" if name in required else "?"}: {ts_type(value)};'
            for name, value in properties.items()
        ]
        additional = schema.get('additionalProperties')
        if isinstance(additional, dict):
            members.append(f'[key: string]: {ts_type(additional)};')
        return '{ ' + ' '.join(members) + ' }' if members else 'Record<string, unknown>'
    return {'string': 'string', 'integer': 'number', 'number': 'number',
            'boolean': 'boolean', 'null': 'null'}.get(kind, 'unknown')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    spec = yaml.safe_load(SPEC.read_text())
    output = '// Generated by scripts/generate_types.py from OpenAPI. Do not edit.\n'
    for name, schema in spec['components']['schemas'].items():
        output += f'export type {name} = {ts_type(schema)};\n'
    target = PACKAGE / 'src/schema.ts'
    if args.check:
        if not target.exists() or target.read_text() != output:
            parser.exit(1, 'SDK types differ from OpenAPI; run scripts/generate_types.py.\n')
    else:
        target.write_text(output)


if __name__ == '__main__':
    main()
